-- insert into eduLVL (eduLvlID, eduLvlName, eduLvlDesc)
--             values (
--                     eduLvlID,
--                     'eduLvlName',
--                     'eduLvlDesc'
--                    )