-- insert into clearances (clearanceID, clName, clDesc)
--             values (
--                     clearanceID,
--                     'clName',
--                     'clDesc'
--                    );