-- insert into sponsors (sponsorID, sponsorName, sponsorDesc)
--             values (
--                     sponsorID,
--                     'sponsorName',
--                     'sponsorDesc'
--                    )