-- insert into clearances (CMID, empID, startDate, endDate)
--             values (
--                     CMID,
--                     empID,
--                     'startDate',
--                     'endDate'
--                    );